language: r

r:
  - oldrel
  - release
  - devel

apt_packages:
  - openjdk-8-jdk

install:
  - R CMD javareconf
  - R -e 'install.packages(c("testthat"))'
  - R -e 'devtools::install_deps(dep = T)'

before_script:
  - cd java
  - make
  - cd ..

script:
  - R CMD build .
  - R CMD check *tar.gz
