language: r

apt_packages:
  - openjdk-8-jdk

before_install:
  - R CMD javareconf

before_script:
  - cd java
  - make
  - cd ..

script:
  - R -e 'install.packages(c("testthat"))'
  - R CMD build . --no-build-vignettes --no-manual
  - R CMD check *tar.gz --no-build-vignettes --no-manual
